# Generated by Django 2.0.4 on 2018-04-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter_one', models.CharField(max_length=30)),
                ('fighter_two', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Combate',
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
                ('skills', models.IntegerField(verbose_name='Habilidades')),
                ('force', models.IntegerField(verbose_name='Fuerza')),
                ('resistance', models.IntegerField(verbose_name='Resistencia')),
            ],
            options={
                'verbose_name': 'Luchador',
                'verbose_name_plural': 'Luchadores',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Torneo',
            },
        ),
        migrations.AddField(
            model_name='combat',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightgame.Tournament', verbose_name='Torneo'),
        ),
    ]
