# Generated by Django 2.0.4 on 2018-04-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightgame', '0002_tournament_fighters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combat',
            old_name='fighter_one',
            new_name='fighter1',
        ),
        migrations.RenameField(
            model_name='combat',
            old_name='fighter_two',
            new_name='fighter2',
        ),
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.IntegerField(choices=[(0, 'Pluma'), (1, 'Medio'), (2, 'Pesado')], default=0, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='alias',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='force',
            field=models.IntegerField(default=0, verbose_name='Fuerza'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='resistance',
            field=models.IntegerField(default=0, verbose_name='Resistencia'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='skills',
            field=models.IntegerField(default=0, verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
    ]
