# Generated by Django 2.0.4 on 2018-04-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fightgame', '0003_auto_20180423_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf1', to='fightgame.Fighter', verbose_name='Torneo'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf2', to='fightgame.Fighter', verbose_name='Torneo'),
        ),
    ]
