# Generated by Django 2.0.4 on 2018-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightgame', '0004_auto_20180423_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='alias',
            field=models.CharField(max_length=20),
        ),
    ]
