# Generated by Django 2.0.4 on 2018-04-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fightgame', '0005_auto_20180423_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_winner', to='fightgame.Fighter', verbose_name='Ganador'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf1', to='fightgame.Fighter', verbose_name='Luchador 1'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf2', to='fightgame.Fighter', verbose_name='Luchador 2'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='alias',
            field=models.CharField(max_length=20, verbose_name='Alias'),
        ),
    ]
