# Generated by Django 2.0.4 on 2018-04-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fightgame', '0008_auto_20180424_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combat',
            name='looser',
        ),
        migrations.AddField(
            model_name='combat',
            name='loser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='combat_loser', to='fightgame.Fighter', verbose_name='Perdedor'),
            preserve_default=False,
        ),
    ]
